[package]
name = "blog-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
diesel = { version = "2.2.4", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.210", features = ["derive"] }
